package:
  name: solar_travel_gui
  version: "0.06"
  
source:
  path: ../
  
build:
  number: 0
  #noarch: python
  entry_points:
    - solar_travel_gui = solar_travel_gui.__main__:main
  osx_is_app: True

requirements:
  host:
    - python
    - setuptools
    - pyqtgraph
    - PyOpenGL
    - pyproj
    - py4design
    - gdal
  run:
    - python
    - pyqtgraph
    - PyOpenGL
    - pyproj
    - py4design
    - gdal
test:
  imports:
    - solar_travel_gui
app:
 entry: solar_travel_gui
 summary: This is an app to visualise solar and travel data
 type: desk

about:
  home: https://github.com/chenkianwee/xxxx
  license: GPL3